//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 

package com.subra.funding.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {  "response"
})
@XmlRootElement(name = "fmxresponse")
public class Fmxresponse<T> {

    @XmlElement(required = true)
    //protected List<Fmxresponse.Response> response;
    protected List<Response<T>> response;

    public List<Response<T>> getResponse() {
        if (response == null) {
            response = new ArrayList<Response<T>>();
        }
        return this.response;
    }
    
    public Fmxresponse() {}

	public Fmxresponse(List<Response<T>> response) {
		super();
		this.response = response;
	}

	public void setResponse(List<Response<T>> response) {
		this.response = response;
	}

	@Override
	public String toString() {
		return "Fmxresponse [response=" + response + "]";
	}

    
}
