//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 


package com.drfbets.funding.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

        @XmlRootElement(name = "result")
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {           "balance"    })
        public class GeneralOperationResponseResult {

            @XmlElement(required = true)
            protected List<Balance> balance;
            

            public GeneralOperationResponseResult(List<Balance> balance) {
				super();
				this.balance = balance;
			}


			public GeneralOperationResponseResult() {
				super();
			}
            

			public List<Balance> getBalance() {
                if (balance == null) {
                    balance = new ArrayList<Balance>();
                }
                return this.balance;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
           // @XmlType(name = "", propOrder = {   "type",    "amount"    })
            @XmlType(name = "", propOrder = {   "type",    "amount" , "damount"   })
            public static class Balance {

                @XmlElement(required = true)
                protected String type;
                @XmlElement(required = true)
               // protected Double amount;
                protected String amount;
                
                @XmlElement(required=false)
                protected Double damount;

                public Balance() {
					super();
					System.out.println("-------------------1----------------------");
				}
                
				//public Balance(String type, Double amount) {
                public Balance(String type, String amount) {
					super();
					this.type = type;
					this.amount = amount;
/*					String strBalance = amount.replaceAll(",", "");
					System.out.println("-------------------2----------------------");
					this.damount = Double.valueOf(strBalance);*/
				}


				public String getType() {
                    return type;
                }
         
                public void setType(String value) {
                    this.type = value;
                }
            
                //public Double getAmount() {
                public String getAmount() {
                    return amount;
                }

//                public void setAmount(Double value) {
                public void setAmount(String value) {
                	//System.out.println("-------------------3----------------------");
                    this.amount = value;
                   // this.damount = Double.valueOf(value);
                }

				@Override
				public String toString() {
					//System.out.println("-------------------4----------------------");
					return "Balance [type=" + type + ", amount=" + amount + ", double-amount=" + damount +  "]";
				}

				public Double getDamount() {
					//System.out.println("-------------------5----------------------");
					return damount;
				}

				public void setDamount(Double damount) {
					//System.out.println("-------------------6----------------------");
					this.damount = damount;
				}

            }

			@Override
			public String toString() {
				return "GeneralOperationResponseResult [balance=" + balance
						+ "]";
			}

        }