//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 

package com.drfbets.funding.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "param")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "account", "type", "id", "subid",
		"fundingmethodid", "details", "amount" })
public class TransactionSendRequestParam {

	@XmlElement(required = true)
	protected BigInteger account;
	@XmlElement(required = true)
	protected String type;
	@XmlElement(required = true)
	protected String id;
	protected String subid;
	protected Integer fundingmethodid;
	@XmlElement(required = true)
	protected Details details;
	@XmlElement(required = true)
	protected Amount amount;

	public BigInteger getAccount() {
		return account;
	}

	public TransactionSendRequestParam(BigInteger account, String type,
			String id, String subid, Integer fundingmethodid, Details details,
			Amount amount) {
		super();
		this.account = account;
		this.type = type;
		this.id = id;
		this.subid = subid;
		this.fundingmethodid = fundingmethodid;
		this.details = details;
		this.amount = amount;
	}

	public TransactionSendRequestParam() {
		super();

	}

	public void setAccount(BigInteger value) {
		this.account = value;
	}

	public String getType() {
		return type;
	}

	public void setType(String value) {
		this.type = value;
	}

	public String getId() {
		return id;
	}

	public void setId(String value) {
		this.id = value;
	}

	public String getSubid() {
		return subid;
	}

	public void setSubid(String value) {
		this.subid = value;
	}

	public Integer getFundingmethodid() {
		return fundingmethodid;
	}

	public void setFundingmethodid(Integer value) {
		this.fundingmethodid = value;
	}

	public Details getDetails() {
		return details;
	}

	public void setDetails(Details value) {
		this.details = value;
	}

	public Amount getAmount() {
		return amount;
	}

	public void setAmount(Amount value) {
		this.amount = value;
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "base", "fee" })
	public static class Amount {

		@XmlElement(required = true)
		protected Double base;
		protected List<Fee> fee;

		
		
		public Amount() {
			super();
		}

		public Amount(Double base, List<Fee> fee) {
			super();
			this.base = base;
			this.fee = fee;
		}


		public Double getBase() {
			return base;
		}

		public void setBase(Double value) {
			this.base = value;
		}

		public List<Fee> getFee() {
			if (fee == null) {
				fee = new ArrayList<Fee>();
			}
			return this.fee;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "type", "amount" })
		public static class Fee {

			@XmlElement(required = true)
			protected String type;
			@XmlElement(required = true)
			protected Double amount;

			
			public Fee() {
				super();
			
			}

			public Fee(String type, Double amount) {
				super();
				this.type = type;
				this.amount = amount;
			}

			public String getType() {
				return type;
			}

			public void setType(String value) {
				this.type = value;
			}

			public Double getAmount() {
				return amount;
			}

			public void setAmount(Double value) {
				this.amount = value;
			}

			@Override
			public String toString() {
				return "Fee [type=" + type + ", amount=" + amount + "]";
			}

		}// Fee

		@Override
		public String toString() {
			return "Amount [base=" + base + ", fee=" + fee + "]";
		}

	} // Amount

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "field" })
	public static class Details {

		protected List<Field> field;

		
		public Details() {
			super();
		}

		public Details(List<Field> field) {
			super();
			this.field = field;
		}
		

		public List<Field> getField() {
			if (field == null) {
				field = new ArrayList<Field>();
			}
			return this.field;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "name", "value" })
		public static class Field {

			@XmlElement(required = true)
			protected String name;
			@XmlElement(required = true)
			protected String value;

			public Field() {
				super();
			
			}

			public Field(String name, String value) {
				super();
				this.name = name;
				this.value = value;
			}

			public String getName() {
				return name;
			}

			public void setName(String value) {
				this.name = value;
			}

			public String getValue() {
				return value;
			}

			public void setValue(String value) {
				this.value = value;
			}

			@Override
			public String toString() {
				return "Field [name=" + name + ", value=" + value + "]";
			}

		} // Field

		@Override
		public String toString() {
			return "Details [field=" + field + "]";
		}

	}// Details

	@Override
	public String toString() {
		return "TransactionSendRequestParam [account=" + account + ", type="
				+ type + ", id=" + id + ", subid=" + subid
				+ ", fundingmethodid=" + fundingmethodid + ", details="
				+ details + ", amount=" + amount + "]";
	}

}
