// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 

package com.drfbets.funding.model;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "account",  "type"  })
@XmlRootElement(name = "param")
public class GeneralOperationRequestParam {

    @XmlElement(required = true)
    protected BigInteger account;
    @XmlElement(required = true)
    protected String type;

    public GeneralOperationRequestParam() {	}
    
    public GeneralOperationRequestParam(BigInteger account, String type) {
		super();
		this.account = account;
		this.type = type;
	}

	public BigInteger getAccount() {
        return account;
    }

    public void setAccount(BigInteger value) {
        this.account = value;
    }

    public String getType() {
        return type;
    }

    public void setType(String value) {
        this.type = value;
    }
	
    @Override
	public String toString() {
		return "GeneralOperationRequestParam [account=" + account + ", type="
				+ type + "]";
	}

}
